FROM ubuntu:20.04

ARG TF_VERSION="1.3.6"


RUN apt-get update \
    && apt-get install --fix-missing -y  ssh\
                                        git\ 
                                        curl\
                                        wget\
                                        zip\
                                        tree\
                                        groff\
                                        python3-pip\
                                        vim\
    &&  apt-get clean \ 
    && rm -rf /var/lib/apt/lists/*

RUN wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

RUN unzip awscliv2.zip && ./aws/install

RUN unzip terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/ \
    && chmod 755 /usr/local/bin/terraform \
    && rm -f terraform_${TF_VERSION}_linux_amd64.zip

COPY requirements.txt /root/requirements.txt
RUN pip3 install -r /root/requirements.txt
